server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  application:
    name: medisphere-api-gateway

  cloud:
    gateway:
      routes:

        # ================= APPOINTMENT =================
        - id: appointment-service
          uri: http://appointment-service:8081
          predicates:
            - Path=/appointments/**
          filters:
            - RewritePath=/appointments/(?<segment>.*), /api/v1/appointments/${segment}

        # ================= PAYMENT =================
        - id: payment-service
          uri: http://payment-service:8082
          predicates:
            - Path=/payments/**
          filters:
            - RewritePath=/payments/(?<segment>.*), /api/v1/payments/${segment}

        # ================= AUTH =================
        - id: auth-service
          uri: http://auth-service:8083
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /api/v1/auth/${segment}

        # ================= PATIENT =================
        - id: patient-service
          uri: http://patient-service:8084
          predicates:
            - Path=/patients/**
          filters:
            - RewritePath=/patients/(?<segment>.*), /api/v1/patients/${segment}

        # ================= DOCTOR =================
        - id: doctor-service
          uri: http://doctor-service:8085
          predicates:
            - Path=/doctors/**
          filters:
            - RewritePath=/doctors/(?<segment>.*), /api/v1/doctors/${segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG