server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  application:
    name: medisphere-api-gateway

  cloud:
    gateway:
      routes:

        # ================= APPOINTMENT =================
        - id: appointment-service
          uri: http://appointment-service:8081
          predicates:
            - Path=/api/appointments/**
          filters:
            - RewritePath=/api/appointments/(?<segment>.*), /api/v1/appointments/${segment}

        # ================= PAYMENT =================
        - id: payment-service
          uri: http://payment-service:8082
          predicates:
            - Path=/api/payment/**
          filters:
            - RewritePath=/api/payment/(?<segment>.*), /api/v1/payment/${segment}

        # ================= AUTH =================
        - id: auth-service
          uri: http://auth-service:8083
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /api/v1/auth/${segment}

        # ================= PATIENT =================
        - id: patient-service
          uri: http://patient-service:8084
          predicates:
            - Path=/api/patients/**
          filters:
            - RewritePath=/api/patients/(?<segment>.*), /patient/api/v1/${segment}

        # ================= DOCTOR =================
        - id: doctor-service
          uri: http://doctor-service:8085
          predicates:
            - Path=/api/doctors/**
          filters:
            - RewritePath=/api/doctors/(?<segment>.*), /doctor/api/v1/${segment}

        # ================= NOTIFICATION =================
        - id: notification-service
          uri: http://notification-service:8087
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/notifications/(?<segment>.*), /api/v1/notifications/${segment}

        # ================= ADMIN =================
        - id: admin-service
          uri: http://admin-service:8089
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/admin/(?<segment>.*), /api/v1/admin/${segment}

        # ================= AI SYMPTOM CHECK =================
        - id: medisphere-AIsymptomcheck-service
          uri: http://medisphere-AIsymptomcheck-service:8088
          predicates:
            - Path=/api/symptoms/**
          filters:
            - RewritePath=/api/symptoms/(?<segment>.*), /api/symptoms/${segment}

        # ================= TELEMEDICINE (SESSIONS) =================
        - id: medisphere-telemedicine-service-sessions
          uri: http://medisphere-telemedicine-service:8086
          predicates:
            - Path=/api/sessions/**
          filters:
            - RewritePath=/api/sessions/(?<segment>.*), /api/sessions/${segment}

        # ================= TELEMEDICINE (PRESCRIPTIONS) =================
        - id: medisphere-telemedicine-service-prescriptions
          uri: http://medisphere-telemedicine-service:8086
          predicates:
            - Path=/api/prescriptions/**
          filters:
            - RewritePath=/api/prescriptions/(?<segment>.*), /api/prescriptions/${segment}

gateway:
  whitelist-urls:
    - /api/v1/auth/register/patient
    - /api/v1/auth/register/doctor
    - /api/v1/auth/login
    - /eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG